apiVersion: apps/v1
kind: Deployment
metadata:
  name: laboratory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laboratory
  template:
    metadata:
      labels:
        app: laboratory
    spec:
      containers:
        - name: laboratory
          image: ghcr.io/nebovarenkovstepan/methods_of_programming_cenn_tki_341/laboratory:c907a25ae393c952a1d2d6fe41e91fb714c779de
          env:
            - name: DATABASE_URL
              value: postgresql://hospital:hospital_password@postgres:5432/hospital_db
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: INTEGRITY_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: integrity-secret
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "hospital-kafka-kafka-bootstrap.kafka:9092"
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 15