apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm
  template:
    metadata:
      labels:
        app: llm
    spec:
      containers:
        - name: llm
          image: ghcr.io/nebovarenkovstepan/methods_of_programming_cenn_tki_341/llm:2591341c0668e8fb6eafe4bb814fff576b8c2ab3
          env:
            - name: DATABASE_URL
              value: postgresql://hospital:hospital_password@postgres:5432/hospital_db
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: INTEGRITY_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: integrity-secret
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 15