apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm
  template:
    metadata:
      labels:
        app: llm
    spec:
      containers:
        - name: llm
          image: ghcr.io/nebovarenkovstepan/methods_of_programming_cenn_tki_341/llm:40379b190fd4bd109e04452689a1e59d1832bee3
          env:
            - name: DATABASE_URL
              value: postgresql://hospital:hospital_password@postgres:5432/hospital_db
            - name: PYTHONUNBUFFERED
              value: "1"
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 15