apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
        - name: portal
          image: ghcr.io/nebovarenkovstepan/methods_of_programming_cenn_tki_341/portal:9df2f6f23ba0a30e68d8cf92497e27dc49b5a472
          env:
            - name: DATABASE_URL
              value: "postgres://hospital:hospital_password@postgres:5432/hospital_db?sslmode=disable"
            - name: PORT
              value: "8080"
            - name: INTEGRITY_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: integrity-secret
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15