apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
        - name: portal
<<<<<<< HEAD
          image: ghcr.io/nebovarenkovstepan/methods_of_programming_cenn_tki_341/portal:latest
=======
          image: ghcr.io//portal:73b7f5b8e17fec52a4d4421b3000a1e247beae0a
>>>>>>> 3a6798ff1d7438d7f1272280ad592ba16ce25650
          env:
            - name: DATABASE_URL
              value: "postgres://hospital:hospital_password@postgres:5432/hospital_db?sslmode=disable"
            - name: PORT
              value: "8080"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15