apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-operator
  namespace: argocd
spec:
  project: default

  source:
    repoURL: oci://quay.io/strimzi-helm
    chart: strimzi-kafka-operator
    targetRevision: 1.0.0
    helm:
      values: |
        watchNamespaces:
          - kafka

        resources:
          requests:
            memory: 384Mi
            cpu: 100m
          limits:
            memory: 384Mi
            cpu: 1000m

  destination:
    server: https://kubernetes.default.svc
    namespace: kafka

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true